Repository SSU-BackStreet/UE5-BackStreet, pull requests merged in 2023-07, with the labels that each got.

#121 [inventory-feature] 무기 인벤토리 로직 수정
  Source/BackStreet/Item/private/WeaponInventoryBase.cpp
  Source/BackStreet/Item/public/WeaponInventoryBase.h
Labels: enhancement

#122 [Inventory-feature -> develop] 인벤토리 로직 수정
  Source/BackStreet/Item/private/WeaponInventoryBase.cpp
  Source/BackStreet/Item/public/WeaponInventoryBase.h
Labels: enhancement

#123 [fix] 무기 인벤토리 Remove 로직 수정
  Content/Map/Development/BattleTestRoom.umap
  Content/UI/Global/Blueprint/BlurTest.uasset
  Source/BackStreet/Item/private/WeaponInventoryBase.cpp
  Source/BackStreet/Item/public/WeaponInventoryBase.h
Labels: bug fix

#126 [battlesystem-feature -> develop] AI 관련 크래시 수정, 타격감 관련 로직 개선 등
  Content/Character/EnemyCharacter/AI/BT_Enemy.uasset
  Content/Character/EnemyCharacter/BotTypeA/Animation/AB_BotTypeA.uasset
  Content/Character/EnemyCharacter/BotTypeA/Animation/Montage/AM_BodyHit.uasset
  Content/Character/EnemyCharacter/BotTypeA/Animation/Montage/AM_HeadHit.uasset
  Content/Character/EnemyCharacter/BotTypeA/Animation/Sequence/AS_BodyHit.uasset
  Content/Character/EnemyCharacter/BotTypeA/Animation/Sequence/AS_HeadHit.uasset
  Content/Character/EnemyCharacter/BotTypeA/BP_EnemyCharacter_TypeA_Melee.uasset
  Content/Character/EnemyCharacter/BotTypeB/Animation/Montage/AM_BodyHit.uasset
  Content/Character/EnemyCharacter/BotTypeB/Animation/Montage/AM_HeadHit.uasset
  Content/Character/EnemyCharacter/BotTypeB/Animation/Sequence/AS_BodyHit.uasset
  Content/Character/EnemyCharacter/BotTypeB/Animation/Sequence/AS_HeadHit.uasset
  Content/Character/MainCharacter/Animation/IKR_CuteCardboardBoy.uasset
  Content/Map/Development/BattleTestRoom.umap
  Content/Map/MainMenu/MainMenuPersistent.umap
  Content/System/AssetManager/Data/D_CharacterAnimAssetInfoTable.uasset
  Source/BackStreet/AISystem/private/BTStateManageServiceBase.cpp
  Source/BackStreet/Character/private/CharacterBase.cpp
  Source/BackStreet/Character/private/EnemyCharacterBase.cpp
  Source/BackStreet/Character/public/AbilityManagerBase.h
  Source/BackStreet/Character/public/CharacterInfoEnum.h
  Source/BackStreet/Character/public/EnemyCharacterBase.h
  Source/BackStreet/Item/private/MeleeWeaponBase.cpp
Labels: enhancement, bug fix

#128 [craftsystem-feature->develop] CraftBox 기능 구현
  .gitignore
  Content/UI/InGame/Blueprint/Component/Crafting/CraftingSlot/WB_CraftingSlotSet.uasset
  Content/UI/InGame/Blueprint/Component/Crafting/InventorySlot/WB_CraftingInventorySingleSlot.uasset
  Content/UI/InGame/Blueprint/Component/Crafting/InventorySlot/WB_CraftingInventorySlotSet.uasset
  Content/UI/InGame/Blueprint/Component/Crafting/WB_CraftingUI.uasset
  Content/Weapon/Blueprint/Crafting/BP_CraftBoxBase.uasset
  Content/Weapon/Data/CraftingRecipe/D_CraftingRecipeTable.csv
  Content/Weapon/Data/CraftingRecipe/D_CraftingRecipeTable.uasset
  Content/Weapon/Data/CraftingRecipe/F_CraftingRecipe.uasset
  Content/Weapon/Data/D_WeaponStatTable.csv
  Content/Weapon/Data/D_WeaponStatTable.uasset
  Source/BackStreet/Character/private/MainCharacterBase.cpp
  Source/BackStreet/CraftingSystem/private/CraftBoxBase.cpp
  Source/BackStreet/CraftingSystem/public/CraftBoxBase.h
  Source/BackStreet/Item/private/WeaponInventoryBase.cpp
  Source/BackStreet/Item/public/WeaponInfoStruct.h
  Source/BackStreet/Item/public/WeaponInventoryBase.h
Labels: ✨new feature

#129 [stagesystem feature -> develop] 스테이지 시스템 관련 GC 리팩토링 완료
  Content/BP_BackStreetGameMode.uasset
  Content/Map/InGame/InGame.umap
  Content/Map/InGame/Lobby.umap
  Content/UI/InGame/Blueprint/Component/WB_MiniMap.uasset
  Source/BackStreet/Global/private/BackStreetGameModeBase.cpp
  Source/BackStreet/Global/public/BackStreet.h
  Source/BackStreet/StageSystem/private/ChapterManagerBase.cpp
  Source/BackStreet/StageSystem/private/GateBase.cpp
  Source/BackStreet/StageSystem/private/ResourceManager.cpp
  Source/BackStreet/StageSystem/private/StageGenerator.cpp
  Source/BackStreet/StageSystem/private/TransitionManager.cpp
  Source/BackStreet/StageSystem/public/ChapterManagerBase.h
  Source/BackStreet/StageSystem/public/GateBase.h
  Source/BackStreet/StageSystem/public/ResourceManager.h
  Source/BackStreet/StageSystem/public/StageData.h
  Source/BackStreet/StageSystem/public/StageGenerator.h
  Source/BackStreet/StageSystem/public/StageInfoStruct.h
  Source/BackStreet/StageSystem/public/TransitionManager.h
Labels: enhancement

#130 [develop->master] AI 버그 수정, 무기 관련 데이터테이블 json
  Content/Map/MainMenu/MainMenuPersistent.umap
  Content/Weapon/Data/D_ProjectileStatTable.csv
  Content/Weapon/Data/D_ProjectileStatTable.json
  Content/Weapon/Data/D_ProjectileStatTable.uasset
  Content/Weapon/Data/D_WeaponStatTable.csv
  Content/Weapon/Data/D_WeaponStatTable.json
  Content/Weapon/Data/D_WeaponStatTable.uasset
  Source/BackStreet/AISystem/private/BTStateManageServiceBase.cpp
  Source/BackStreet/Character/private/EnemyCharacterBase.cpp
  Source/BackStreet/Character/public/CharacterBase.h
  Source/BackStreet/Character/public/CharacterInfoStruct.h
  Source/BackStreet/Character/public/EnemyCharacterBase.h
Labels: enhancement, bug fix

#131 [feat] CraftBox UI 적용 및 기타 버그 수정
  Content/BP_BackStreetGameMode.uasset
  Content/Item/Blueprint/Item_Weapon/BP_WeaponItem_BareHand_Brick.uasset
  Content/Map/InGame/InGame.umap
  Content/Map/InGame/Lobby.umap
  Content/Map/MainMenu/MainMenuPersistent.umap
  Content/UI/InGame/Blueprint/Component/Crafting/CraftingSlot/WB_CraftingSlotSet.uasset
  Content/UI/InGame/Blueprint/Component/Crafting/InventorySlot/WB_CraftingInventorySingleSlot.uasset
  Content/UI/InGame/Blueprint/Component/Crafting/InventorySlot/WB_CraftingInventorySlotSet.uasset
  Content/UI/InGame/Blueprint/Component/Crafting/WB_CraftingUI.uasset
  Content/UI/InGame/Blueprint/Component/WB_MiniMap.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_BackGroundCraft.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_BottonCraft.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_BottonCraft_Active.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_Dummy.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_ExitIcon.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_ExitIcon_Active.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_InvetoryBox.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_InvetoryBox_Hover.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_InvetoryBox_Selected.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_ProgressBox.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_ProgressIcon.uasset
  Content/UI/InGame/Texture/CraftingBox/TX_ResultBox.uasset
  Content/Weapon/Data/CraftingRecipe/D_CraftingRecipeTable.csv
  Content/Weapon/Data/CraftingRecipe/D_CraftingRecipeTable.json
  Content/Weapon/Data/CraftingRecipe/D_CraftingRecipeTable.uasset
  Content/Weapon/Data/D_ProjectileStatTable.csv
  Content/Weapon/Data/D_ProjectileStatTable.json
  Content/Weapon/Data/D_ProjectileStatTable.uasset
  Content/Weapon/Data/D_WeaponStatTable.csv
  Content/Weapon/Data/D_WeaponStatTable.json
  Content/Weapon/Data/D_WeaponStatTable.uasset
  Source/BackStreet/AISystem/private/BTStateManageServiceBase.cpp
  Source/BackStreet/Character/private/EnemyCharacterBase.cpp
  Source/BackStreet/Character/public/CharacterBase.h
  Source/BackStreet/Character/public/CharacterInfoStruct.h
  Source/BackStreet/Character/public/EnemyCharacterBase.h
  Source/BackStreet/Global/private/BackStreetGameModeBase.cpp
  Source/BackStreet/Global/public/BackStreet.h
  Source/BackStreet/Item/public/ItemBase.h
  Source/BackStreet/StageSystem/private/ChapterManagerBase.cpp
  Source/BackStreet/StageSystem/private/GateBase.cpp
  Source/BackStreet/StageSystem/private/ResourceManager.cpp
  Source/BackStreet/StageSystem/private/StageGenerator.cpp
  Source/BackStreet/StageSystem/private/TransitionManager.cpp
  Source/BackStreet/StageSystem/public/ChapterManagerBase.h
  Source/BackStreet/StageSystem/public/GateBase.h
  Source/BackStreet/StageSystem/public/ResourceManager.h
  Source/BackStreet/StageSystem/public/StageData.h
  Source/BackStreet/StageSystem/public/StageGenerator.h
  Source/BackStreet/StageSystem/public/StageInfoStruct.h
  Source/BackStreet/StageSystem/public/TransitionManager.h
Labels: ✨new feature
